# Generated by Django 4.1.4 on 2023-01-22 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_watering',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 20, 55, 24, 788935)),
        ),
    ]
