# Generated by Django 4.1.4 on 2023-01-24 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0002_userplant_location_alter_userplant_last_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='next_watering',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_watering',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
