# Generated by Django 4.1.4 on 2023-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0003_userplant_next_watering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='next_watering',
            field=models.DateTimeField(),
        ),
    ]
