# Generated by Django 4.1.4 on 2023-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0006_alter_userplant_next_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='last_watering',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
