# Generated by Django 4.1.4 on 2023-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0009_alter_plant_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
