# Generated by Django 4.1.4 on 2023-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_garden', '0010_alter_plant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='watering_level',
            field=models.CharField(choices=[('skąpe', 'skąpe'), ('umiarkowane', 'umiarkowane'), ('obfite', 'obfite'), ('bardzo obfite', 'bardzo obfite')], max_length=32),
        ),
    ]
